name: Setup Node and Install Dependencies
description: Configure Node.js with caching and install npm dependencies.

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '22'
  cache-dependency-path:
    description: Path to package-lock.json for cache key (optional)
    required: false
    default: ''
  working-directory:
    description: Working directory for install command
    required: false
    default: '.'

outputs:
  cache-path:
    description: Resolved cache dependency path for downstream steps
    value: ${{ steps.resolve-cache-path.outputs.path }}

runs:
  using: composite
  steps:
    # IMPORTANT: Workflows must handle checkout explicitly to avoid running dependency installation
    # against untrusted code in privileged contexts (CodeQL rule actions/untrusted-checkout/critical).
    - name: Determine cache dependency path
      id: resolve-cache-path
      shell: bash
      run: |
        set -euo pipefail
        input_path="${{ inputs.cache-dependency-path }}"
        workdir="${{ inputs.working-directory }}"

        if [ -n "$input_path" ]; then
          echo "path=$input_path" >> "$GITHUB_OUTPUT"
        else
          case "$workdir" in
            ""|".")
              echo "path=package-lock.json" >> "$GITHUB_OUTPUT"
              ;;
            *)
              trimmed="${workdir%/}"
              echo "path=$trimmed/package-lock.json" >> "$GITHUB_OUTPUT"
              ;;
          esac
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ steps.resolve-cache-path.outputs.path }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
